name: 'Test Secret'
description: 'Testing Action'
inputs:
  env:  # id of input
    description: 'Get the Environment'
    required: true
    default: 'dev'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        env="${{ inputs.env }}"
        echo "you entered ${{ inputs.env }}".
        echo "env value is : $env"
