name: 'Test custom action'
on : [ workflow_dispatch ]
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: 'test action'
      id: tester
      uses: raghunath1986/composite-action@master
      with: 
        env: 'dev'
    
